name: Dependabot Pull Requests

on:
  workflow_run:
    workflows:
      - Pull Requests
    types:
      - completed

permissions:
  contents: write

jobs:
  dependabot-changeset:
    name: Create changeset for Dependabot
    if: github.event.workflow_run.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - uses: actions/cache@v4
        id: cache-node_modules
        with:
          path: node_modules
          key: ubuntu-latest-20-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ubuntu-latest-20-${{ hashFiles('**/package-lock.json') }}
      - if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Configure git for Dependabot
        run: |
          git config --global user.name "$(git show -s --format='%an' ${{ github.event.workflow_run.head_sha }})"
          git config --global user.email "$(git show -s --format='%ae' ${{ github.event.workflow_run.head_sha }})"
      - name: Create changeset
        run: |
          COMMIT_BODY=$(git show -s --format='%b' "${{ github.event.workflow_run.head_sha }}")
          SUMMARY=$(echo "${COMMIT_BODY}" | head -1)
          CHANGESET_FILE=".changeset/dependabot-${{ github.event.workflow_run.pull_requests.id }}.md"
          echo -e "---" >| $CHANGESET_FILE
          echo -e "lint-staged: patch" >> $CHANGESET_FILE
          echo -e "---\n" >> $CHANGESET_FILE
          echo "$SUMMARY" >> $CHANGESET_FILE
          git add $CHANGESET_FILE
      - id: diff
        name: Check changeset diff
        continue-on-error: true
        run: git diff --staged --exit-code -- .changeset/dependabot-${{ github.event.workflow_run.pull_requests.id }}.md
      - name: Update PR with changeset
        if: steps.diff.outcome == 'failure'
        run: |
          git add .
          git commit --amend --no-edit
          git push --force --force-with-lease
